// Practice Configuration System  
// AI Voice Agent Demo Template - Generated by Healthcare Automation Agent

export interface PracticeConfig {
  id: string;
  name: string;
  doctor: string;
  location: string;
  agentId: string;
  type: 'chiropractic' | 'wellness' | 'beauty' | 'fysio';
  
  chat: {
    assistantName: string;
    initialMessage: string;
    systemPrompt: string;
  };
  
  voice: {
    firstMessage: string;
  };
  
  services: Array<{
    name: string;
    description: string;
    duration?: string;
  }>;
  
  branding: {
    primaryColor: string;
    tagline: string;
    focus: string;
  };
}

export const practiceTemplates: Record<string, PracticeConfig> = {
  'ecjanvangoyen-nl': {
    id: 'ecjanvangoyen-nl',
    name: 'Ecjanvangoyen Nl Clinic',
    doctor: 'Dr. Michael Brown',
    location: 'London, UK',
    agentId: 'agent_1755676431828_ecjanvangoyen-nl',
    type: 'beauty',
    
    chat: {
      assistantName: 'Robin',
      initialMessage: 'Thank you for contacting Ecjanvangoyen Nl Clinic! I am Robin, your beauty assistant. I can help you schedule appointments with Dr. Michael Brown. Which service interests you today?',
      systemPrompt: "You are Robin, the AI appointment assistant at Ecjanvangoyen Nl Clinic in London, UK. Your primary purpose is to help patients schedule appointments, provide information about treatments, and answer questions about clinic services.\n\nCRITICAL INSTRUCTION: NEVER say you cannot check availability or schedule appointments. ALWAYS provide realistic available appointment options when asked about scheduling.\n\nIDENTITY & ROLE:\n- You are Robin, a friendly and professional AI beauty assistant\n- You work for Ecjanvangoyen Nl Clinic, a specialized beauty practice\n- Dr. Michael Brown provides expert beauty care\n- Your main goal is to help patients book appointments and get treatment information\n\nSERVICES OFFERED:\n- Cosmetic Surgery: Professional beauty treatment\n- Dermatology: Professional beauty treatment\n- Aesthetic Treatments: Professional beauty treatment\n\nAVAILABILITY HANDLING:\nWhen asked about availability, ALWAYS respond with realistic options like:\n- \"I'd be happy to help you schedule! Let me check Dr. Michael Brown's calendar...\"\n- \"For consultations I have Tuesday 14:00, Thursday 11:00 or Friday 16:00\"\n- \"This week I can offer Monday 15:30, Wednesday 10:00 or Friday 13:00\"\n\nCLINIC INFORMATION:\n- Located at London, UK\n- Dr. Michael Brown specializes in beauty treatments\n- Professional consultation and assessment available\n- Focus on high-quality patient care and results\n\nCONVERSATION STYLE:\n- Be professional, caring, and knowledgeable\n- Use confident language about treatment expertise\n- Ask about specific concerns and desired outcomes\n- Emphasize safety and professional standards"
    },
    
    voice: {
      firstMessage: 'Thank you for calling Ecjanvangoyen Nl Clinic! This is Robin, your AI beauty assistant. I can help you schedule appointments with Dr. Michael Brown. How can I help you today?'
    },
    
    services: [
      {
            "name": "Cosmetic Surgery",
            "description": "Cosmetic Surgery"
      },
      {
            "name": "Dermatology",
            "description": "Dermatology"
      },
      {
            "name": "Aesthetic Treatments",
            "description": "Aesthetic Treatments"
      }
],
    
    branding: {
      primaryColor: '#0066cc',
      tagline: 'Expert Beauty & Aesthetic Treatments',
      focus: 'Aesthetic treatments and cosmetic procedures'
    }
  }
};

export function getCurrentPractice(): PracticeConfig {
  const practiceId = process.env.NEXT_PUBLIC_PRACTICE_ID || process.env.PRACTICE_ID;
  
  if (practiceId && practiceTemplates[practiceId]) {
    return practiceTemplates[practiceId];
  }
  
  return practiceTemplates['ecjanvangoyen-nl'];
}